### ISSUE TITLE
How to point CTS Dev server to Ona

### ISSUE THREAD

**Issue by aqueiroz** [theirc/CTS#35]
Hi Guys

I've managed to login, create users, kits, packages and shipments...
I also managed to setup my android device with Ona. 
I think the last piece is to get my dev CTS to pull data out of my submissions in Ona.
Where or how would i achieve that?

Cant wait to start scaning my QR codes and viewing them on the map.

Thank you so much in advance.

Regards

Andre

**Comment by aqueiroz** [comment]
Hi Guys, can no one help? really stuck on this one.

Thanks in advance

Andre

**Comment by vkurup** [comment]
The Ona interface is documented in the deployment docs: https://cts-ircdeploy.readthedocs.org/en/latest/ona.html

The development server is not currently set up to poll Ona, but you can copy these settings from staging.py to local.py and it _should_ work: https://github.com/theirc/CTS/blob/develop/cts/settings/staging.py#L78-L83

The tricky one's are the FORM_IDs since the IRC currently uses a self-hosted version of Ona that is older than the public ona.io. You should be able to find your FORM ID (an integer) by using their API. This link might work after replacing owner with your Ona username: https://api.ona.io/api/v1/forms?owner=vkurup I'm afraid I don't know of a better, more failsafe way to do that, so you may have to play around to find the right ID.

**Comment by watsonj** [comment]
Thanks Vinod. 

Andre, the IRC is moving to Ona.io, so you should def use that

**Comment by aqueiroz** [comment]
Guys thanks for the reply. I will try to make sense of all of it at the
weekend.

Appreciate it.

Andre

**Comment by aqueiroz** [comment]
Hi Guys started fresh!!!
Following the documentation Vinod suggested .

I dont quite understand it. stuch at the SSH-RSA bit... i did create a new
key.... than what.

I think im getting confused with dev, and prod... i know the difference,
but it seems im missing something.

Fresh install on my VM... Clonned the git, installed all pre-requisits,
created Virtual env. now what? just does not seem clear what needs to be
done.

I cannot get the keys, as my test user cannot login to the amazon servers
to get them.

Please help... dont want to give up on project.

PS vinod... managed to get form ID.

Regards

Andre

On 24 February 2016 at 19:11, Andre Queiroz andy1979s@gmail.com wrote:

> Guys thanks for the reply. I will try to make sense of all of it at the
> weekend.
> 
> Appreciate it.
> 
> Andre
> On 24 Feb 2016 17:22, "Jake Watson" notifications@github.com wrote:
> 
> > Thanks Vinod.
> > 
> > Andre, the IRC is moving to Ona.io, so you should def use that
> > 
> > Sent from my iPhone
> > 
> > > On Feb 24, 2016, at 4:47 PM, Vinod Kurup notifications@github.com
> > > wrote:
> > > 
> > > The Ona interface is documented in the deployment docs:
> > > https://cts-ircdeploy.readthedocs.org/en/latest/ona.html
> > > 
> > > The development server is not currently set up to poll Ona, but you can
> > > copy these settings from staging.py to local.py and it should work:
> > > https://github.com/theirc/CTS/blob/develop/cts/settings/staging.py#L78-L83
> > > 
> > > The tricky one's are the FORM_IDs since the IRC currently uses a
> > > self-hosted version of Ona that is older than the public ona.io. You
> > > should be able to find your FORM ID (an integer) by using their API. This
> > > link might work after replacing owner with your Ona username:
> > > https://api.ona.io/api/v1/forms?owner=vkurup I'm afraid I don't know of
> > > a better, more failsafe way to do that, so you may have to play around to
> > > find the right ID.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/theirc/CTS/issues/35#issuecomment-188360470.

## 

Dre

Http://www.brazilartsandcrafts.com
http://www.brazilianchef.co.uk/ http://www.foodiefanatic.co.uk/

**Comment by aqueiroz** [comment]
guys latest update.
think im almost there.

Just need a bit more hand holding.

So i have my Dev server running. what i need to know is:

Where and what to add to the local.py in order to access my API.ona.io form data.

https://api.ona.io/api/v1/forms?owner=andreq

Vinod do i just add this bit?

# ONA related settings

ONA_DOMAIN = os.environ.get('ONA_DOMAIN%s' % INSTANCE_SUFFIX, 'ona.io')
ONA_API_ACCESS_TOKEN = os.environ.get('ONA_API_ACCESS_TOKEN%s' % INSTANCE_SUFFIX, '')
ONA_FORM_IDS = os.environ.get('ONA_FORM_IDS%s' % INSTANCE_SUFFIX, '11983').split(';')  # noqa
ONA_DEVICEID_VERIFICATION_FORM_ID = \
    os.environ.get('ONA_DEVICEID_VERIFICATION_FORM_ID%s' % INSTANCE_SUFFIX, '0')

into the default local.py?
do i need to add more? specifi any variables?

could i have an example please?
as there is also a stagin.py file. and i using the wrong thing?

when i try to add anything to my local.py i get lots of errors when i try to run the server.

think we are close to get this running.

Maybe we could have a chat? when is the best time to get you guys online?

thank you so much for the help.

regards

Andre

**Comment by vkurup** [comment]
Let's pretend your Ona access token is 'ABC123', your FormID is '4321' and your Ona DeviceID FormID is '5678'.

Then, in local.py, you would add this:

```
# ONA related settings
ONA_DOMAIN = 'ona.io'  
ONA_API_ACCESS_TOKEN = 'ABC123'
ONA_FORM_IDS = ['4321']
ONA_DEVICEID_VERIFICATION_FORM_ID = '5678'
```

I am not sure, but you may need to try 'api.ona.io' for the ONA_DOMAIN, if this doesn't work.

**Comment by aqueiroz** [comment]
I did try that then the console started throwing errors.

I added those lines to my local.py and got errors. What do I do?

Guys I'm willing to help with the documentation.  If I get this working.

**Comment by aqueiroz** [comment]
Cool, that worked.... now if i understand well. Thanks Vinod.
Now what? 
I've created a catalogue a shipment with packages.
on my phone I scanned my user QRcode and also a done a test submit of a package.

I cn see the data in api.ona.io

How does CTS pulls the data? and how i can see it in the map... when i click on it the map comes up but i cant see my shipment.

thank you so so much for the help.

Regards

Andre

**Comment by aqueiroz** [comment]
hi guys, any ideas?
Am i missing a step?
got the ona.io details into my local.py file.

created a shipment. entered all details, finalized it.
scanned my user qrcode with phone, submited forms to ona.io

now what, do i need to tell CTS to get it? how do i see my shipment in the Map?

sorry for being a pain, im sure you guys are pretty busy.

Thank you so much for all the help so far.

regards

Andre

**Comment by watsonj** [comment]
CTS should poll Ona for updates and update the DB accordingly … so the status of a scanned package should change in the system.

**Comment by aqueiroz** [comment]
Thanks Jake. .. I had it on the whole day and nothing changed.
I'm missing something that seems to be very clear to you guys.

Maybe the form I'd?

But truly not sure... it's a shame.

Any other ideas?

An example of how I should go about would help.

The only thing that has a qr code is the user. How is that associated to my
shipment?

Maybe let me know what to check. And let me know a few steps to create a
new shipment. And test it. Otherwise you will be guessing what I'm doing
too.

Thank you so much

**Comment by watsonj** [comment]
Just to be clear, you did the following:
Created a shipment in CTS, and produced the QR codes for the packages in this shipment
Have configured/linked CTS with Ona.io, and do not see errors in the CTS
Have configured ODK Collect on your mobile device to use the Package Delivery Form using the account Ona.io account configured above
Have scanned and completed the ODK Form on your mobile device, and confirmed that your expected record/form is viewable on Ona.io
Rechecked your logs — any warnings or errors?

**Comment by aqueiroz** [comment]
The answer to everything is yes.
The only thing that seems weird is.
Like I said the only place I see qr codes is my user.
My shipment does not have one. My packages do not have one?

Where would I look for it within the shipment/ package?

The rest is all done. Mobile is setup correctly. It sends data up to
api.ona.io
I can see the data.

But like I said the qr code I scanned into the form was my user qr.

Thank you for the help.

Andre

**Comment by watsonj** [comment]
Have you actually read all of the documentation?
http://cts-project.readthedocs.org/en/stable/user/index.html

Where are you getting the QR code if not from the packages within your shipment in CTS?

**Comment by aqueiroz** [comment]
I have... only mentions user qr ....
Also as an example. One of the forms is the user device one. I scan my user
qr. If I understand well that should assign my device Id with my user
account. It has not so far. I checked online at ona.io. and the data is
there. But cts has not pulled the data from ona.

As Vinod mentioned I have added the details to local.py

Not sure what else to do.

Once I'm sure the data is being pulled from ona to my test environment I
can tackle the usage and packages qr.

Thank you for the help

**Comment by watsonj** [comment]
Once u have a shipment with packages, go to the 'print' menu - that will generate the package codes. The user codes only work for tying the device is to the user and uses a different form.

**Comment by aqueiroz** [comment]
I will try tomorrow. Thank you.

But back to my original point. I did use the user device capture form. So
my cts is not pulling data from ona. That's the main issue.

Chat later 😊

**Comment by watsonj** [comment]
No, it is that your form didn't match the expected input. In other words, it wasn't a package code, thus there was no update to the package.

**Comment by aqueiroz** [comment]
ok... finally mnaged to get the right qrcode for my shipment/ package. from print menu, package barcode. did another submit from my phone scanner the correct qr code.
Waited a while to see if CTS would pull the data and nothing.

here are my forms https://api.ona.io/api/v1/forms?owner=andreq

here is my code within local.py

# ONA related settings

ONA_DOMAIN = 'api.ona.io'  
ONA_API_ACCESS_TOKEN = 'my token'
ONA_FORM_IDS = ['243804']
ONA_DEVICEID_VERIFICATION_FORM_ID = '243812'

my guess is i got something wrong in the code?

could you please help.

thank you very much

andre

**Comment by watsonj** [comment]
Logs?
Code works fine

**Comment by vkurup** [comment]
My guess is that this is an another artifact of running the project locally, rather than in a deployed setup. Local setup 'emulates' background tasks using the `CELERY_ALWAYS_EAGER = True` setting, but it does not emulate background _scheduled_ tasks, which are listed [here](https://github.com/theirc/CTS/blob/develop/cts/settings/base.py#L280-L295).

Try running this command:

```
python manage.py update_package_locations
```

That command should ping Ona for any Package forms matching your `ONA_FORM_IDS` setting.

**Comment by aqueiroz** [comment]
hmmmm got a few errors:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dude/virtualenvs/cts/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/dude/virtualenvs/cts/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/dude/virtualenvs/cts/local/lib/python2.7/site-packages/django/conf/**init**.py", line 48, in **getattr**
    self._setup(name)
  File "/home/dude/virtualenvs/cts/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dude/virtualenvs/cts/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/dude/virtualenvs/cts/CTS-develop/cts/**init**.py", line 5, in <module>
    from .celery import app as celery_app  # noqa
  File "/home/dude/virtualenvs/cts/CTS-develop/cts/celery.py", line 12, in <module>
    if not getattr(settings, 'CELERY_ALWAYS_EAGER', False):
  File "/home/dude/virtualenvs/cts/local/lib/python2.7/site-packages/django/conf/**init**.py", line 48, in **getattr**
    self._setup(name)
  File "/home/dude/virtualenvs/cts/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dude/virtualenvs/cts/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named local

**Comment by aqueiroz** [comment]
Last update

Hi Guys

manage to get around errors:

(cts) dude@ubuntu:~/virtualenvs/cts/CTS-develop$ export PYTHONPATH=/usr/local/lib/python2.7/site-packages
(cts) dude@ubuntu:~/virtualenvs/cts/CTS-develop$ #!/usr/bin/env python manage.py update_package_locations
(cts) dude@ubuntu:~/virtualenvs/cts/CTS-develop$ 

got no errors....

gave some time , went to shipments selected my shipment and nothing on the map. 

so close... 

please advise.

thank you

**Comment by aqueiroz** [comment]
Ok just to confirm... I went back to my ONA settings and notice that i had used wrong form IDs

# ONA related settings

ONA_DOMAIN = 'api.ona.io'  
ONA_API_ACCESS_TOKEN = 'my token'
ONA_FORM_IDS = ['107907']
ONA_DEVICEID_VERIFICATION_FORM_ID = '107906'

this is now correct

i then ran #!/usr/bin/env python manage.py update_package_locations within my virtual env and got no errors.

still cant see my shipment in the map.

Which logs would tell me what is happening?

thank you guys... we are almost there.....

**Comment by aqueiroz** [comment]
Hi guys any ideas?

**Comment by aqueiroz** [comment]
Hi Vinod No ideas then? Is there a way i can try the production version instead? Will still run it via a VM from home. I just need to get it working to see how it performs. 

Sorry for all the hustle and thanks for the help.  

BTW: ran your command python manage.py update_package_locations gotr no errors, but still cannot see my packages on the map.

Regards

Andre
